name: bob_env

channels:
  - conda-forge

dependencies:
  - python=3.9
  - aicsimageio
  - bioformats_jar
  - scikit-image=0.19.3
  - pandas
  - seaborn
  - jupyterlab
  - matplotlib
  - scikit-learn
  - stackview
  - scipy
  - numpy
  - skan
  - pyclesperanto-prototype
  - pillow


  